[pytest]
addopts = -p no:cacheprovider
python_files = pytest_*.py
norecursedirs =
    .git
    .pytest_cache
    .test-tmp
    .test_tmp
    __pycache__
    dist
    *.egg-info
    pytest-cache-files-*
